services:
  tautulli:
    container_name: ${SERVICES_TAUTULLI_CONTAINER_NAME:-tautulli}
    hostname: ${SERVICES_TAUTULLI_HOSTNAME:-tautulli}
    image: ${SERVICES_TAUTULLI_IMAGE:-lscr.io/linuxserver/tautulli}:${SERVICES_TAUTULLI_IMAGE_VERSION:-latest}
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./tautulli/config:/config
    # ports:
    #   - 8181:8181
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.entrypoints=homesec
      - traefik.http.routers.tautulli.rule=Host(`${DOMAIN}`)
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:8181]/files/
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tautulli-logo.png
    restart: always
    networks:
      - frontend
networks:
  frontend:
    external: true
