#-------------------------------------------- routers --------------------------------------------#
http:
  routers:
    jetkvm:
      entryPoints:
        - "homesec"
      rule: "Host(`jetkvm.yourdomain.com`)"
      service: jetkvm
      tls: {}


    krusader:
      entryPoints:
        - "homesec"
      rule: "Host(`krusader.yourdomain.com`)"
      service: krusader
      tls: {}

    skynet:
      entryPoints:
        - "homesec"
      rule: "Host(`skynet.yourdomain.com`)"
      service: skynet
      tls: {}

#-------------------------------------------- services --------------------------------------------#

  services:
    jetkvm:
      loadBalancer:
        servers:
          - url: "http://192.168.20.199"

    krusader:
      loadBalancer:
        servers:
          - url: "http://192.168.20.3:6080"
          # - url: "http://192.168.20.3:6080/vnc.html?resize=remote&host=192.168.20.3&port=6080&autoconnect=1"

    skynet:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
          - url: "https://192.168.20.3:1443"
