# VERWENDE DAS OFFIZIELLE BUILDER-IMAGE
FROM caddy:2.10.0-builder AS builder

# INSTALLIERE DIE NEUESTE XCADDY-VERSION UND LEERE DEN GO-CACHE,
# UM SICHERZUSTELLEN, DASS ALLES SAUBER IST
RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
RUN go clean -modcache

# FÜHRE DEN BUILD-BEFEHL MIT EXPLIZITER VERSION AUS
RUN xcaddy build v2.10.0 \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/hslatman/caddy-crowdsec-bouncer/http \
    --with github.com/hslatman/caddy-crowdsec-bouncer/layer4 \
    --with github.com/hslatman/caddy-crowdsec-bouncer/appsec

# DAS FINALE IMAGE
FROM caddy:2.10.0

COPY --from=builder /usr/bin/caddy /usr/bin/caddy