services:
  vorta:
    image: ghcr.io/borgbase/vorta-docker:latest
    container_name: vorta
    hostname: vorta
    # cap_add:
    #   - SYS_ADMIN
    #    security_opt:
    #      - apparmor:unconfined
    privileged: true
    volumes:
      - ./vorta:/config
      - /mnt/user:/data:ro
      - /mnt/user/test:/destination
      #- /volumeUSB1/:/destination
    ports:
      - 5811:5800
    restart: unless-stopped
    environment:
      - USER_ID=99
      - GROUP_ID=100
      - TZ=Europe/Berlin
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    labels:
      - traefik.enable=true
      - traefik.docker.network=backend
      - traefik.http.routers.vorta.entrypoints=homesec
      - traefik.http.routers.vorta.rule=Host(`vorta.${DOMAIN}`)
      - net.unraid.docker.webui=http://[IP]:[PORT:5811]/
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/borgbase/vorta/93ef64cddeb361d7d16035826b4e85988e32a0b3/src/vorta/assets/icons/icon.svg
    networks:
      - backend
networks:
  backend:
    external: true
