templates:
  my_gradient_template:
    optional:
      level
    overlay:
      name: <<n>>
      file: <<file>>
    plex_all: true
    builder_level: <<level>>    


overlays:
  gradient:
    template: {name: my_gradient_template, file: config/overlays/jmxd/gradient.png, n: gradient}

  gradient-season:
    template: {name: my_gradient_template, file: config/overlays/jmxd/org_gradient.png, n: gradient-s, level: season}

  gradient-episode:
    template: {name: my_gradient_template, file: config/overlays/jmxd/gradient_episode.png, n: gradient-e, level: episode}
  
  gradient-episode-bottom:
    template: {name: my_gradient_template, file: config/overlays/jmxd/gradient_episode_bottom.png, n: gradient-e2, level: episode}    