services:
  filebrowser:
    container_name: filebrowser
    hostname: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 99:100
    healthcheck:
      disable: true
    ports:
      - 99:80
    volumes:
      - ${DATA_DIR}:/srv
      - ./filebrowser:/config
      - ./filebrowser:/database
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.filebrowser.entrypoints=websecure,homesec
      - traefik.http.routers.filebrowser.rule=Host(`fb.${DOMAIN}`)
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:99]/files/
      - net.unraid.docker.icon=https://github.com/maschhoff/docker/raw/master/filebrowser/35781395.png
      - net.unraid.docker.shell=sh
      - pangolin.proxy-resources.filebrowser.name=filebrowser
      - pangolin.proxy-resources.filebrowser.full-domain=fb.${DOMAIN}
      - pangolin.proxy-resources.filebrowser.protocol=http
      - pangolin.proxy-resources.filebrowser.auth.sso-enabled=true
      - pangolin.proxy-resources.filebrowser.targets[0].method=http
      - pangolin.proxy-resources.filebrowser.targets[0].hostname=filebrowser
      - pangolin.proxy-resources.filebrowser.targets[0].port=80
      - pangolin.proxy-resources.filebrowser.rules[0].action=pass
      - pangolin.proxy-resources.filebrowser.rules[0].match=country
      - pangolin.proxy-resources.filebrowser.rules[0].value=DE
      - pangolin.proxy-resources.filebrowser.rules[0].priority=1
      - pangolin.proxy-resources.filebrowser.rules[1].action=deny
      - pangolin.proxy-resources.filebrowser.rules[1].match=country
      - pangolin.proxy-resources.filebrowser.rules[1].value=ALL
      - pangolin.proxy-resources.filebrowser.rules[1].priority=2
    networks:
      - frontend
networks:
  frontend:
    external: true
