http:

  ## EXTERNAL ROUTING EXAMPLE - Only use if you want to proxy something manually ##
  # routers:
  #   # proxmox routing example - Remove if not used
  #   proxmox:
  #     entryPoints:
  #       - websecure
  #     rule: 'Host(`proxmox.example.com`)'
  #     service: proxmox
  #     # middlewares:
  #       # - "auth"  
  # ## SERVICES EXAMPLE ##
  # services:
  #   # proxmox service example - Remove if not used
  #   proxmox:
  #     loadBalancer:
  #       servers:
  #         - url: https://192.168.178.4:8006

  ## MIDDLEWARES ##
  middlewares:
    # Only Allow Local networks
    local-ipwhitelist:
      ipAllowList:
        sourceRange:
          - 127.0.0.1/32 # localhost
          - 10.0.0.0/8 # LAN Subnet
          - 192.168.178.0/24 # LAN Subnet

    authelia:
        forwardAuth:
            address: http://authelia:9091/api/verify?rd=https://auth.example.com # change example.com to your domain
            trustForwardHeader: true
            authResponseHeaders:
              - "Remote-User"
              - "Remote-Groups"
              - "Remote-Email"
              - "Remote-Name"

    crowdsec:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          Enabled: true
          CrowdsecLapiKey: your_key # docker exec -t crowdsec cscli bouncers add bouncer-traefik
          CrowdsecLapiHost: "crowdsec:8080"
          CrowdsecMode: "stream"
          # CrowdsecAppsecEnabled: true
          # CrowdsecAppsecHost: "crowdsec:7422"
          forwardedHeadersCustomName: X-Custom-Header

          # enabled: true
          # logLevel: DEBUG
          # updateIntervalSeconds: 30
          # updateMaxFailure: 0
          # defaultDecisionSeconds: 30
          # httpTimeoutSeconds: 10
          # crowdsecMode: live
          # crowdsecAppsecEnabled: false
          # crowdsecAppsecHost: crowdsec:7422
          # crowdsecAppsecFailureBlock: true
          # crowdsecAppsecUnreachableBlock: true
          # crowdsecLapiKey: your_key
          # crowdsecLapiKeyFile: /etc/traefik/cs-privateKey-foo
          # crowdsecLapiHost: crowdsec:8080
          # crowdsecLapiScheme: http
          # crowdsecLapiTLSInsecureVerify: false
          # crowdsecCapiMachineId: login
          # crowdsecCapiPassword: password
          # crowdsecCapiScenarios:
          #   - crowdsecurity/http-path-traversal-probing
          #   - crowdsecurity/http-xss-probing
          #   - crowdsecurity/http-generic-bf
          # forwardedHeadersTrustedIPs: 
          #   - 0.0.0.0/0
          #   - 10.0.20.0/24
          # clientTrustedIPs: 
            # - 192.168.178.0/24
          # forwardedHeadersCustomName: X-Custom-Header
          # redisCacheEnabled: false
          # redisCacheHost: "redis:6379"
          # redisCachePassword: v%J^Uz$Sxk5Gi5NtD5pMfx7zM9CBMWuh&H&b9E@J75
          # redisCacheDatabase: "5"
          # crowdsecLapiTLSCertificateAuthority: |-
          #   -----BEGIN CERTIFICATE-----
          #   MIIEBzCCAu+gAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgZQxCzAJBgNVBAYTAlVT
          #   ...
          #   Q0veeNzBQXg1f/JxfeA39IDIX1kiCf71tGlT
          #   -----END CERTIFICATE-----
          # crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/crowdsec-certs/ca.pem
          # crowdsecLapiTLSCertificateBouncer: |-
          #   -----BEGIN CERTIFICATE-----
          #   MIIEHjCCAwagAwIBAgIUOBTs1eqkaAUcPplztUr2xRapvNAwDQYJKoZIhvcNAQEL
          #   ...
          #   RaXAnYYUVRblS1jmePemh388hFxbmrpG2pITx8B5FMULqHoj11o2Rl0gSV6tHIHz
          #   N2U=
          #   -----END CERTIFICATE-----
          # crowdsecLapiTLSCertificateBouncerFile: /etc/traefik/crowdsec-certs/bouncer.pem
          # crowdsecLapiTLSCertificateBouncerKey: |-
          #   -----BEGIN RSA PRIVATE KEY-----
          #   MIIEogIBAAKCAQEAtYQnbJqifH+ZymePylDxGGLIuxzcAUU4/ajNj+qRAdI/Ux3d
          #   ...
          #   ic5cDRo6/VD3CS3MYzyBcibaGaV34nr0G/pI+KEqkYChzk/PZRA=
          #   -----END RSA PRIVATE KEY-----
          # crowdsecLapiTLSCertificateBouncerKeyFile: /etc/traefik/crowdsec-certs/bouncer-key.pem
          # captchaProvider: hcaptcha
          # captchaSiteKey: FIXME
          # captchaSecretKey: FIXME
          # captchaGracePeriodSeconds: 1800
          # captchaHTMLFilePath: /captcha.html
          # banHTMLFilePath: /ban.html

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true

# Only use secure ciphers - https://ssl-config.mozilla.org/#server=traefik&version=2.6.0&config=intermediate&guideline=5.6
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
