services:
  embyserver:
    image: emby/embyserver:latest
    container_name: Emby
    devices:
      - /dev/dri
    ports:
      - 8097:8096/tcp
    environment:
      - UID=99
      - GID=100
      - GIDLIST=100
    volumes:
      - /mnt/user/Media/:/media:ro
      - /dev/shm:/transcode:rw
      - ./Emby:/config:rw
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.emby.entrypoints=websecure,homesec
      - traefik.http.routers.emby.rule=(Host(`emby.${DOMAIN}`))
      - traefik.http.services.emby.loadbalancer.server.port=8096
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://[IP]:[PORT:8096]/
      - net.unraid.docker.icon=https://raw.githubusercontent.com/MediaBrowser/Emby.Resources/master/images/Logos/logoicon.png
      - pangolin.proxy-resources.emby.name=emby
      - pangolin.proxy-resources.emby.full-domain=emby.${DOMAIN}
      - pangolin.proxy-resources.emby.protocol=http
      - pangolin.proxy-resources.emby.auth.sso-enabled=true
      - pangolin.proxy-resources.emby.targets[0].method=http
      - pangolin proxy-resources.emby.targets[0].hostname=filebrowser
      - pangolin.proxy-resources.emby.targets[0].port=8096
      - pangolin.proxy-resources.emby.rules[0].action=pass
      - pangolin.proxy-resources.emby.rules[0].match=country
      - pangolin.proxy-resources.emby.rules[0].value=DE
      - pangolin.proxy-resources.emby.rules[0].priority=1
      - pangolin.proxy-resources.emby.rules[1].action=deny
      - pangolin.proxy-resources.emby.rules[1].match=country
      - pangolin.proxy-resources.emby.rules[1].value=ALL
      - pangolin.proxy-resources.emby.rules[1].priority=2
    restart: unless-stopped
    networks:
      - frontend
  embycreditocr:
    image: yock1/embycreditocr
    container_name: tesseract-ocr
    devices:
      - /dev/dri:/dev/dri
    # ports:
    #   - 8884:8884
    restart: unless-stopped
    networks:
      - frontend
networks:
  frontend:
    external: true
