services:
  recyclarr:
    container_name: ${SERVICES_RECYCLARR_CONTAINER_NAME:-recyclarr}
    hostname: ${SERVICES_RECYCLARR_HOSTNAME:-recyclarr}
    image: ${SERVICES_RECYCLARR_IMAGE:-ghcr.io/recyclarr/recyclarr}:${SERVICES_RECYCLARR_IMAGE_VERSION:-edge}
    user: ${ENV_PUID}:${ENV_PGID}
    read_only: false
    networks:
      - backend
    volumes:
      - ./config:/config
    environment:
      CRON_SCHEDULE: "* 4 * * *"
      TZ: ${TIMEZONE}
    restart: always
networks:
  backend:
    external: true
