services:
  posterizarr:
    container_name: ${SERVICES_POSTERIZARR_CONTAINER_NAME:-posterizarr2}
    hostname: ${SERVICES_POSTERIZARR_HOSTNAME:-posterizarr2}
    image: ${SERVICES_POSTERIZARR_IMAGE:-ghcr.io/fscorrupt/docker-posterizarr}:${SERVICES_POSTERIZARR_IMAGE_VERSION:-latest}
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
      - UMASK=022
      - TERM=xterm
      - RUN_TIME=12:00 #,19:30
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - ./config/posterizarr:/config:rw
      - ./config/posterizarr/assets:/assets:rw
      - ./config/posterizarr/assetsbackup:/assetsbackup:rw
      - ./config/posterizarr/manualassets:/manualassets:rw
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/posterizarr-icon.png
networks:
  frontend:
    external: true
