services:
  glances:
    restart: unless-stopped
    container_name: Glances
    image: nicolargo/glances:latest
    network_mode: bridge
    environment:
      - TZ=Europe/Berlin
      - GLANCES_OPT=-w
    ports:
      - 61208:61208/tcp
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances/glances.conf:/etc/glances/glances.conf:rw
    labels:
      - net.unraid.docker.managed=dockerman
      - 'net.unraid.docker.webui=http://[IP]:[PORT:61208]/'
      - 'net.unraid.docker.icon=https://github.com/nicolargo/glances/raw/master/glances/outputs/static/images/glances.png'
    pid: host
networks: {}
