services:
  webtop:
    image: ${SERVICES_WEBTOP_IMAGE:-ghcr.io/xpipe-io/xpipe-webtop}:${SERVICES_WEBTOP_IMAGE_VERSION:-latest}
    container_name: ${SERVICES_WEBTOP_CONTAINER_NAME:-xpipe-webtop}
    hostname: ${SERVICES_WEBTOP_HOSTNAME:-xpipe-webtop}
    environment:
      - CUSTOM_PORT=6077
      - CUSTOM_HTTPS_PORT=6078
      - TITLE="XPIPE Terminal"
      - START_DOCKER=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - ./xpipe/config:/config  # Hier wird das neue Volume hinzugefügt
    ports:
      - 6077:6077
      - 6078:6078
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    external: true
