services:
  audiobook:
    container_name: ${SERVICES_AUDIOBOOK_CONTAINER_NAME:-audiobook}
    hostname: ${SERVICES_AUDIOBOOK_HOSTNAME:-audiobook}
    image: ${SERVICES_AUDIOBOOK_IMAGE:-ghcr.io/advplyr/audiobookshelf}:${SERVICES_AUDIOBOOK_IMAGE_VERSION:-latest}
    healthcheck:
      disable: true
    restart: unless-stopped
    ports:
      - 13378:80
    volumes:
      - ${DATA_DIR}:/audiobooks
      - ./audiobookshelf:/config
      - ./audiobookshelf/metadata:/metadata
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.entrypoints=websecure,homesec
      - traefik.http.routers.audiobookshelf.rule=Host(`ab.${DOMAIN}`)
      - traefik.http.routers.audiobookshelf.middlewares=authelia@file
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:80]
      - net.unraid.docker.icon=https://github.com/advplyr/audiobookshelf/raw/master/client/static/Logo.png
    networks:
      - frontend
networks:
  frontend:
    external: true
