collections:
  High Quality Label:
    build_collection: false
    item_label: HighQuality
    plex_all: true
    filters:
      filepath.regex: 
      - '(?i)\b(BluRay)\b'
      #- '(?i)\b(Web)\b'
      - '(?i)\b(WEBDL)\b'
      - '(?i)\b(WEBRip)\b'
  Trakt Trending:
    trakt_chart:
      chart: watched
      limit: 8
    minimum_items: 1
    schedule: weekly(wednesday|thursday|friday|saturday|sunday)
    collection_order: custom
    sync_mode: sync
    collection_mode: hide
    name: Trending
    visible_library: true
    visible_home: true
    visible_shared: true
    radarr_add_missing: false
    radarr_search: false
    item_radarr_tag.sync: pmm
  Bud Spencer and Terence Hill:
    plex_search:
      any:
        actor: 
         - Bud Spencer
         - Terence Hill
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    sort_title: "!140_Bud Spencer and Terence Hill"
  Ben Stiller:
    tmdb_actor: 7399
    sync_mode: sync
    collection_order: title.asc
    collection_mode: show_items
    sort_title: "!140_Ben Stiller"
  Disney Remakes:
    trakt_list: https://trakt.tv/lists/11139648
    sync_mode: sync
    collection_order: custom
    sort_title: "!070_Walt Disney Remakes"
    collection_mode: hide_items
  Animation:
    trakt_list: https://trakt.tv/lists/20492879
    sync_mode: append
    sort_title: "!030_Animation"
    collection_order: title.asc




    