services:
  mydrive:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: mydrive_production
    # env_file:
    # - ./backend/config/.env.production
    volumes:
      - .:/usr/app-production
      - /usr/app-production/node_modules
      - ${FS_DIRECTORY}:/data
    ports:
      - ${HTTP_PORT:-3000}:3000
      - ${HTTPS_PORT:-8080}:8080
    environment:
      - DOCKER=true
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    external: true
