services:
  traefik:
    container_name: ${SERVICES_TRAEFIK_CONTAINER_NAME:-traefik}
    hostname: ${SERVICES_TRAEFIK_HOSTNAME:-traefik}
    image: ${SERVICES_TRAEFIK_IMAGE:-traefik}:${SERVICES_TRAEFIK_IMAGE_VERSION:-latest} #docker.io/library/traefik:latest
    depends_on:
      crowdsec:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
      - 8183:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/:/etc/traefik/
      - ./config/logs:/var/log/traefik
    environment:
      - IPV64_API_KEY=${IPV64_API_KEY}
      # - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN # Cloudflare
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.docker.network=frontend
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:8183]/
      - net.unraid.docker.icon=https://raw.githubusercontent.com/ibracorp/unraid-templates/master/icons/traefik.png
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
      - backend
    restart: unless-stopped
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./config/authelia/config:/config
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls=true
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN}
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:9091]/
      - net.unraid.docker.icon=https://raw.githubusercontent.com/ibracorp/app-logos/main/authelia/authelia.png
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    healthcheck:
      disable: true
  crowdsec:
    container_name: ${SERVICES_CROWDSEC_CONTAINER_NAME:-crowdsec}
    hostname: ${SERVICES_CROWDSEC_HOSTNAME:-crowdsec}
    image: ${SERVICES_CROWDSEC_IMAGE:-crowdsecurity/crowdsec}:${SERVICES_CROWDSEC_IMAGE_VERSION:-latest}
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - cscli
        - version
      timeout: 2s
      interval: 20s
      retries: 5
      start_period: 10s
    ports:
      - 8081:8080/tcp
      - 6060:6060/tcp
      - 7422:7422/tcp
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/crowdsec/data/:/var/lib/crowdsec/data:rw
      - ./config/crowdsec/:/etc/crowdsec:rw
      - ./config/logs:/var/log/traefik/:ro
      - ../jellyfin/jellyfin/log:/var/log/jellyfin/:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
    environment:
      - TZ=${TIMEZONE}
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve
        crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching
        crowdsecurity/sshd crowdsecurity/linux crowdsecurity/base-http-scenarios
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:8081]/
      - net.unraid.docker.icon=https://raw.githubusercontent.com/ibracorp/app-logos/main/crowdsec/crowdsec.png
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
networks:
  frontend:
    external: true
  backend:
    external: true
