services:
  nexterm:
    image: germannewsmaker/nexterm:1.0.2-OPEN-PREVIEW
    ports:
      - 6989:6989
    restart: unless-stopped
    volumes:
      - ./nexterm:/app/data
    networks:
      - backend
networks:
  backend:
    external: true
