services:
  nexterm:
    image: ${SERVICES_NEXTERM_IMAGE:-germannewsmaker/nexterm}:${SERVICES_NEXTERM_IMAGE_VERSION:-1.0.2-OPEN-PREVIEW}
    ports:
      - 6989:6989
    restart: unless-stopped
    volumes:
      - ./nexterm:/app/data
    networks:
      - backend
networks:
  backend:
    external: true
