services:
  deemix:
    container_name: deemix
    image: registry.gitlab.com/bockiii/deemix-docker
    environment:
      - DEEMIX_SINGLE_USER=false
      - PUID=3000
      - PGID=3000
    ports:
      - 6595:6595/tcp
    volumes:
      - /mnt/Downloads/:/downloads:rw
      - ./deemix:/config:rw
    networks:
      - backend
networks:
  backend:
    external: true
