services:
  deemix:
    container_name: deemix
    image: registry.gitlab.com/bockiii/deemix-docker:latest
    environment:
      - DEEMIX_SINGLE_USER=false
      - PUID=99
      - PGID=100
    ports:
      - 6595:6595/tcp
    volumes:
      - /mnt/user/home/Downloads/:/downloads:rw
      - ./deemix:/config:rw
    networks:
      - backend
networks:
  backend:
    external: true
