services:
  breitband-desktop:
    image: fabianbees/breitbandmessung:latest
    container_name: breitband-desktop
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./breitbandmessung/data:/config/xdg/config/Breitbandmessung
    ports:
      - 5800:5800
    restart: unless-stopped
    networks:
      - backend
    labels:
      - net.unraid.docker.webui=http://[IP]:[PORT:5800]/
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=s
networks:
  backend:
    external: true
